---

version: '3.8'

services:
  nginx:
    container_name: aus_test_task_nginx
    image: nginx:stable
    build:
      context: ./docker/nginx
    depends_on:
      - php-fpm
    ports:
      - "8001:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./:/project/

  php-fpm:
    container_name: aus_test_task_php-fpm
    image: php:test
    build:
      context: ./docker/php
    depends_on:
      - postgresql
    volumes:
      - ./:/project/
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    command: >
      /bin/bash -c "umask 0002
      && php-fpm
      "

  postgresql:
    container_name: aus_test_task_postgresql
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: austest
      POSTGRES_PASSWORD: austest
      POSTGRES_DB: austest
    ports: [ "5432" ]

volumes:
  postgresql:
