---

version: '3.0'

services:
  nginx:
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/etc/nginx/templates/:/etc/nginx/templates/:ro
      - ./:/project/:ro,delegated

  php-fpm:
    image: php:test
    build:
      context: .
      dockerfile: dockerfiles/php
    volumes:
      - ./docker/php/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/usr/local/etc/php-fpm.d/:/usr/local/etc/php-fpm.d/:ro
      - ./:/project/:delegated
    env_file:
      - ./my.env
    environment:
      COMPOSER_HOME: /project/.composer
    command: >
      /bin/bash -c "umask 0002
      && php-fpm
      "

  postgresql:
    image: postgresql:test
    build:
      context: .
      dockerfile: dockerfiles/postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data/

volumes:
  postgresql:
