customers_get:
    controller: App\Http\Controller\CustomerController::getAll
    methods: GET

customer_get_by_id:
    path: /{customerId}
    controller: App\Http\Controller\CustomerController::getById
    methods: GET
