customers_get:
    path: customers
    controller: App\Http\Controller\CustomerController::getAll
    methods: GET

customer_get_by_id:
    path: customers/{customerId}
    controller: App\Http\Controller\CustomerController::getById
    methods: GET
